import google.generativeai as genai
from openai import OpenAI
from typing import List
from threading import Thread
import os
from LogSettings import logger,logging
from .func1 import Ideator

g_api_key=os.getenv("GEMINI_API_KEY")
GPT_MODEL="gpt-4-0125-preview"
GEMINI_MODEL='gemini-pro'

class Innovator(Ideator):
    def __init__(self,problem:str,ideas:List[str],thread_id:str):
        super().__init__(problem,thread_id)
        self.ideas=ideas
        self.all_improve_idea=[]    

    def scamperMethod(self):
        threads = []
        self.p_changer.changeEvent(f'アイデア向上の発想法を{len(self.ideas)}個呼び出した',self.thread_id)
        for i in range(len(self.ideas)):
            logger.log(logging.INFO,f"scamper(アイデア向上)の{i+1}つ目の呼び出し")
            thread=Thread(target=self._doScamperMethod,args=(self.ideas[i],i+1))
            threads.append(thread)
            thread.start()
        for thread in threads:
            thread.join()    
            
class InnovateGPT(Innovator):
    def __init__(self,problem:str,ideas:List[str]):
        super().__init__(problem,ideas)
        self.client=OpenAI()
        
    def _doScamperMethod(self,origin_idea:dict[str,str,str,str,str],num:int):
        system_message="You are a maker with high creativity and implementation skills. Moving forward, there's a need for you to refine ideas. Please utilize your creativity to come up with effective ideas for the problem at hand."
        
        improve_format="""Idea x:[Idea Name]([technique using in SCAMPER])
core idea:[Explanation of the Core Idea]
Technologies and Materials Used:[What kind of technologies and materials are used]
Revised Approach to Problem-Solving:[How the given problem is solved]
Concrete Use Cases:[List the use cases]"""

        scamper="""SCAMPER Technique: An Enhanced Guide for Creative Innovation
Introduction:\nSCAMPER is a powerful tool for sparking creativity, encouraging innovative thinking by altering existing elements. It stands for Substitute, Combine, Adapt, Modify, Put to other uses, Eliminate, and Reverse.
Incorporating Additional Insights:\nEmphasize that all new ideas are modifications of existing ones, adding or altering components.\nHighlight that the first idea is not always the best, and exploring alternatives can lead to more effective solutions.\nEncourage thinking beyond the immediate challenge, considering how an idea might solve unrelated problems or lead to breakthrough innovations.
Substitute:\nChange parts, materials, or people to improve or alter the function.\nCase Study: Starbucks' continuous substitution led to the creation of the Frappuccino.\nAdditional Insight: Rod Spruel's innovation in creating fireplace fuel from used coffee grounds and candle wax.
Combine:\nMerge different ideas, products, or services for enhanced functionality.\nCase Study: Hungarian architects' combination of cement and glass fiber to create light-transmitting concrete.\nAdditional Insight: How Gutenberg's combination of a wine press and coin punch led to the invention of the printing press.
Adapt:\nBorrow elements from other contexts to solve problems in a new setting.\nCase Study: Jacuzzi's adaptation of farm pumps for hydrotherapy baths.\nAdditional Insight: Jacuzzi's transformation of a simple idea into a luxury bathroom product.
Modify:\nAlter the size, shape, or properties to serve a new purpose.\nCase Study: Moen’s showerheads modified for a unique water flow pattern.\nAdditional Insight: The evolution of Mr. Clean Magic Reach, a bathroom cleaning tool adapted from an observed cleaning technique in Puerto Rico.
Eliminate:\nRemove unnecessary elements to simplify and improve efficiency.\nCase Study: Dutch Boy's reimagined paint packaging for ease of use.\nAdditional Insight: NASA's simplification of space suits for Mars expeditions.
Reverse:\nChange the order or perspective to see things differently.\nCase Study: Cirque du Soleil's reversal of traditional circus concepts.\nAdditional Insight: FBI's undercover operation using a wedding scenario to capture criminals.
Implementing SCAMPER:\nApply SCAMPER to each element of a challenge, exploring new ideas.\nEncourage exploring multiple options and returning to the original idea if it remains the best solution.\nEmphasize the importance of case studies in understanding and applying SCAMPER.
Concluding Thoughts:\nSCAMPER, a checklist of questions, can transform existing ideas into innovative solutions.\nIts flexibility makes it a valuable tool across various industries.\nBy repeatedly applying SCAMPER, one can discover unique, original ideas, fostering innovation and problem-solving."""

        bad_ex="""Mindful Mood Mixer (MMM) (Adapt)\nCore Idea: Mindful Mood Mixer (MMM) is a virtual reality (VR) system that integrates mindfulness and meditation into a personalized VR experience. It adapts a concept similar to Emotional VR, where the VR environment responds to the user's emotional state. In MMM, this environment is tailored to guide users through mindfulness and meditation practices based on their current emotional state, detected through biometric readings. The aim is to provide immediate emotional relief while fostering long-term emotional regulation and resilience through mindfulness techniques.\n"""
        good_ex="""Mindful Mood Mixer (MMM) (Adapt)\nCore Idea: Mindful Mood Mixer (MMM) is a pioneering virtual reality system focused on enhancing mental well-being through personalized mindfulness and meditation experiences. This system uses advanced biometric monitoring to gauge a user's emotional state, then adapts its VR environment accordingly to provide tailored mindfulness and meditation practices. The concept is to offer immediate emotional support while also cultivating long-term emotional resilience and mindfulness skills.\n"""
        
        b_improve_example="""Emotional VR
Core Idea:Emotional VR is an innovative virtual reality system that provides customized emotional experiences based on individual users' emotional states. By analyzing biometric signals such as heart rate and skin conductance to interpret emotions, the system dynamically alters the VR environment based on these readings. This assists users in appropriately controlling their emotions and guiding them in a positive direction. The technology enables users not only to understand their emotions but also to actively manage them and learn methods to reduce stress.
Technologies and Materials Used:The system utilizes sensor technology for biometric signal recognition, machine learning algorithms for emotion analysis, and a 3D graphics engine to create a dynamic VR environment that responds to emotions. Additionally, it incorporates high-quality audio output and voice guides that use a psychological approach to enhance user immersion.
Revised Approach to Problem-Solving:The system accurately reads users' current emotions and provides an environment that either amplifies those emotions or induces relaxation, thereby solving mental health issues. For example, a calming forest scene is provided for users feeling stress, aiding relaxation and supporting emotional control. When positive emotions are detected, the system offers social events within VR to further enhance users' sense of happiness.
Concrete Use Cases:For instance, a user returning home from a tiring day at work can use this system to experience a tranquil walk in the forest tailored to their day's stress level. On weekends, they can relive and share happy moments with family and friends in VR. Additionally, as part of mental health care, users can participate in guided meditation sessions led by psychotherapists in VR
"""
        user_template=f"""Please follow the (guide) below and come up with five ideas that expand on (base_idea). Of course, it is important that these ideas are also ideas that solve (issue).Each idea should be described in about 450 words. However, each idea must conform to the (format). The brackets [] in the format are explanations of what should be written. For example, where it says [specific number], actually insert a specified matter like 2000. Parts like core idea: do not need to be changed.In addition, since developed ideas will be presented on a separate occasion from (base_idea), please do not mention (base_idea) in the idea document, e.g., "improve (base_idea)". In other words, (bad_ex) and (good_ex) are documents about the same idea, but should be written like (good_ex).\n
Format:{improve_format}\n
Guide:{scamper}\n
bad_ex:{bad_ex}\n
good_ex:{good_ex}\n\n"""

        user_example_message=f"""{user_template}
base_idea:{b_improve_example}
problem:How to use information technology to enrich people's emotions"""

        assistant_answer_message="""Idea1:Social Emotion VR (Substitute)\nCore Idea:Social Emotion VR is a groundbreaking virtual reality platform meticulously designed to foster deep emotional connections and community engagement in a digital space. This innovative system enables users to share and communicate their emotional states in real-time with others, creating a support network within the virtual world. It serves as a digital sanctuary for users to seek comfort, understanding, or shared joy, aligning with their emotional needs at any given moment.\nTechnologies and Materials Used:The platform utilizes advanced sensor technology for real-time emotion detection. These sensors are capable of accurately interpreting subtle changes in the user’s emotional state. Combined with sophisticated machine learning models, the platform analyzes emotional data to create a responsive virtual environment that reflects the user’s feelings. It is also equipped with a robust 3D graphics engine, delivering an immersive and visually engaging experience. Additionally, the platform ensures user privacy and safety through secure privacy controls and interactive tools, creating a safe space for emotional expression and management.\nRevised Approach to Problem-Solving:Social Emotion VR takes an innovative approach to mental health by offering adaptive virtual scenarios that mirror users' emotional states. It is designed to encourage a balanced emotional life, where stressful emotions trigger serene and peaceful settings, while joyful states activate interactive and celebratory spaces. This dynamic environment enhances the overall emotional well-being of the user by providing a tailored virtual experience that addresses their current emotional needs.\nConcrete Use Cases:This platform has diverse applications, such as providing a tranquil forest environment for a user dealing with daily stressors, offering a peaceful escape to decompress and relax. Conversely, for those seeking social engagement, it provides vibrant virtual gatherings for interaction and shared joy. The platform also has therapeutic applications, offering guided relaxation sessions developed by mental health professionals, making it a versatile tool for emotional wellness and community building.\n
Idea2:Relaxation Therapy VR(combine)\nCore Idea:Relaxation Therapy VR is not just a tool; it’s a revolution in the world of mental wellness. This system combines the immersive power of virtual reality with scientifically-proven relaxation and meditation techniques. Imagine stepping into a world where every element is tailored to soothe your mind and alleviate stress. The core of this system lies in creating personal sanctuaries, offering users an escape into peaceful landscapes that promote mental clarity and stress reduction. It's like having a personal retreat accessible at any time, right in your home.\nTechnologies and Materials Used:At the heart of Relaxation Therapy VR is environmental biofeedback technology. This advanced system uses physiological markers such as heart rate variability to create a deeply personalized meditation experience. By responding to each user's unique bio-signals, the system adjusts the virtual environment, ensuring maximum relaxation and effectiveness. The combination of serene visuals and sounds, alongside educational content about stress management, forms a comprehensive, holistic approach. This technology doesn't just replicate calming environments; it evolves with the user, creating an ever-improving, personalized relaxation journey.\nRevised Approach to Problem-Solving:Relaxation Therapy VR is designed to tackle stress and anxiety by providing a complete immersion in tranquil virtual environments. The real-time biofeedback ensures that each session is tailored to the individual’s current state, enhancing the effectiveness of relaxation practices. This approach goes beyond traditional relaxation methods, using the latest in VR and biofeedback technology to address stress and anxiety in a modern, personalized way.\nConcrete Use Cases:The versatility of Relaxation Therapy VR is remarkable. Users can engage in guided meditation journeys, participate in virtual yoga classes, or simply relax in beautifully rendered natural environments. The system adapts to various mental health needs, making it an invaluable tool for daily relaxation routines and structured therapeutic programs. Whether for a quick stress-relief session or a comprehensive mental health regimen, Relaxation Therapy VR offers a multitude of engaging and beneficial activities.\n
Idea3:Creative Expression VR(Adapt)\nCore Idea:Creative Expression VR is a groundbreaking platform that redefines artistic expression. This innovative system offers a virtual space where users can harness their emotions and channel them into creative pursuits. The platform allows users to visualize and materialize their feelings using various artistic mediums, transforming the VR space into a canvas for emotional exploration and expression. It’s a therapeutic venture, offering a satisfying and unique outlet for users to express themselves creatively.\nTechnologies and Materials Used:Creative Expression VR is equipped with a diverse array of digital tools. Users can engage in painting, sculpting, music composition, and even virtual performances within a studio setting. It supports a wide range of artistic activities and includes a virtual gallery for community interactions and feedback. This platform is not just about creating art; it's about experiencing and sharing it in a dynamic, interactive environment.\nRevised Approach to Problem-Solving:Using art as a tool for emotional catharsis and personal growth, Creative Expression VR provides a safe and inspiring environment for users to explore and express their innermost feelings. The platform is designed to encourage self-exploration and emotional expression through creative means, offering an innovative approach to dealing with emotional challenges.\nConcrete Use Cases:Creative Expression VR caters to both beginners and seasoned artists. It offers creative workshops, peer sharing opportunities, and exploration of new artistic realms. This platform is especially beneficial for those seeking creative outlets to improve emotional well-being. Whether it’s experimenting with new art forms or refining existing skills, Creative Expression VR provides a space where art and emotion intersect, offering a unique and therapeutic experience for all users.
Idea4:EmoSphere VR(Modify)\nCore Idea:EmoSphere VR represents a significant leap forward in virtual reality technology, introducing a unique spherical display that fully immerses the user in a 360-degree environment. This advanced system is meticulously designed to enhance the user's sensory engagement, delivering a comprehensive and all-encompassing experience that deeply resonates with their emotional states. The primary aim of EmoSphere VR is to create an environment that not only entertains but also deeply connects with the user on an emotional level, providing an unparalleled experience in virtual reality.\nTechnologies and Materials Used:EmoSphere VR integrates a host of sophisticated technologies to achieve its revolutionary experience. At the forefront is the spherical display, which envelopes the user in a fully immersive visual field. This display is complemented by state-of-the-art surround sound systems, creating an auditory experience that is just as rich and enveloping as the visual one. Additionally, the system includes multi-directional haptic feedback mechanisms, allowing users to feel and interact with the virtual environment in a tactile and realistic manner.The system's emotional responsiveness is powered by advanced biometric sensors. These sensors are capable of detecting subtle changes in the user's physiological states, such as heart rate, skin temperature, and even minute facial expressions. Coupled with sophisticated AI algorithms, these sensors allow EmoSphere VR to analyze and respond to the user's emotional state in real-time, adapting the virtual environment to enhance or soothe their emotions.\nRevised Approach to Problem-Solving:The innovative approach of EmoSphere VR lies in its ability to create a virtual environment that is not just visually and audibly immersive but also emotionally resonant. Traditional VR systems focus on visual and auditory immersion, but EmoSphere VR takes this a step further by integrating emotional resonance into the experience. This approach facilitates a deeper level of emotional exploration and healing, as the environment can be tailored to evoke or soothe specific emotions.\nConcrete Use Cases:EmoSphere VR finds its applications in a variety of scenarios. For individuals seeking tranquility and relaxation, the system can immerse them in a serene forest environment, complete with the sounds of nature and a calming visual palette. Every element, from the rustling of leaves to the gentle flow of a stream, is rendered in stunning detail, providing a deeply relaxing experience.
Idea5:Reverse Emotion VR(Reverse)\nCore Idea:Reverse Emotion VR introduces an innovative twist to the virtual reality experience by presenting users with pre-determined emotional environments. This system is designed to challenge the user's emotional adaptability and resilience. Unlike traditional VR systems that cater to the user's current emotional state, Reverse Emotion VR takes the opposite approach. It presents users with a variety of emotional scenarios, requiring them to adapt and respond accordingly. This unique method aims to build emotional strength and flexibility, allowing users to handle a wider range of emotional situations effectively.\nTechnologies and Materials Used:Reverse Emotion VR utilizes established VR technologies, including dynamic environments and precise biometric sensors, to create a responsive and interactive experience. The system's dynamic environments are designed to simulate various emotional scenarios vividly. The biometric sensors play a crucial role in monitoring the user's responses to these scenarios, providing feedback to the system to adjust the experience in real-time.\nRevised Approach to Problem-Solving:The innovative aspect of Reverse Emotion VR is its reversed interaction pattern. Instead of a VR system that adapts to the user's current emotions, it presents pre-set emotional scenarios for the user to experience and adapt to. This reversal challenges the user to practice emotional regulation and adaptability in a controlled yet diverse range of situations, enhancing their ability to handle real-life emotional challenges.\nConcrete Use Cases:Reverse Emotion VR is particularly beneficial in professional training and personal development contexts. For instance, therapists can use this system to prepare themselves for a wide range of emotional situations they might encounter with clients. Educators and first responders can also benefit from this training, as it prepares them to remain calm and focused in high-stress or emotionally charged scenarios.In a personal development context, users can use Reverse Emotion VR to practice and improve their emotional regulation skills. They might be placed in a simulated high-stress environment, such as a busy workplace, and learn techniques to maintain calmness and focus. Conversely, in an environment of overwhelming joy and excitement, users can practice grounding techniques to maintain emotional balance. This system's versatility makes it a valuable tool for anyone looking to enhance their emotional intelligence and resilience."""
        
        
        user_message=f"""{user_template}base_idea:{self.serializeDict(origin_idea)}\nproblem:{self.problem}"""

        message=[
                {"role":"system", "content":system_message},
                {"role":"user", "content":user_example_message },
                {"role":"assistant", "content": assistant_answer_message},
                {"role":"user","content":user_message}]
                
        api_response=self.client.chat.completions.create(model=GPT_MODEL,messages=message,max_tokens=4000,temperature=1.15).choices[0].message.content
        normalized_list=self._extractIdea(api_response)
        print(f"list長:{str(len(normalized_list))}")
        if len(normalized_list)==0:
            print(api_response)
        self.all_improve_idea.extend(normalized_list)
        logger.log(logging.INFO,f"scamper(アイデア向上)の{num}つ目の完了")
        
class InoveteGemini(Innovator):
    def __init__(self, problem: str, ideas: List[str],thread_id:str):
        super().__init__(problem, ideas,thread_id)
        genai.configure(api_key=g_api_key)
        genai.GenerationConfig(candidate_count=1)
        self.client=genai.GenerativeModel(GEMINI_MODEL)
        
    def _doScamperMethod(self,origin_idea:dict[str,str,str,str,str],num:int):
        system_message="You are a maker with high creativity and implementation skills. Moving forward, there's a need for you to refine ideas. Please utilize your creativity to come up with effective ideas for the problem at hand."
        
        improve_format="""Idea x:[Idea Name]([technique using in SCAMPER])
core idea:[Explanation of the Core Idea]
Technologies and Materials Used:[What kind of technologies and materials are used]
Revised Approach to Problem-Solving:[How the given problem is solved]
Concrete Use Cases:[List the use cases]"""

        scamper="""SCAMPER Technique: An Enhanced Guide for Creative Innovation
Introduction:\nSCAMPER is a powerful tool for sparking creativity, encouraging innovative thinking by altering existing elements. It stands for Substitute, Combine, Adapt, Modify, Put to other uses, Eliminate, and Reverse.
Incorporating Additional Insights:\nEmphasize that all new ideas are modifications of existing ones, adding or altering components.\nHighlight that the first idea is not always the best, and exploring alternatives can lead to more effective solutions.\nEncourage thinking beyond the immediate challenge, considering how an idea might solve unrelated problems or lead to breakthrough innovations.
Substitute:\nChange parts, materials, or people to improve or alter the function.\nCase Study: Starbucks' continuous substitution led to the creation of the Frappuccino.\nAdditional Insight: Rod Spruel's innovation in creating fireplace fuel from used coffee grounds and candle wax.
Combine:\nMerge different ideas, products, or services for enhanced functionality.\nCase Study: Hungarian architects' combination of cement and glass fiber to create light-transmitting concrete.\nAdditional Insight: How Gutenberg's combination of a wine press and coin punch led to the invention of the printing press.
Adapt:\nBorrow elements from other contexts to solve problems in a new setting.\nCase Study: Jacuzzi's adaptation of farm pumps for hydrotherapy baths.\nAdditional Insight: Jacuzzi's transformation of a simple idea into a luxury bathroom product.
Modify:\nAlter the size, shape, or properties to serve a new purpose.\nCase Study: Moen’s showerheads modified for a unique water flow pattern.\nAdditional Insight: The evolution of Mr. Clean Magic Reach, a bathroom cleaning tool adapted from an observed cleaning technique in Puerto Rico.
Eliminate:\nRemove unnecessary elements to simplify and improve efficiency.\nCase Study: Dutch Boy's reimagined paint packaging for ease of use.\nAdditional Insight: NASA's simplification of space suits for Mars expeditions.
Reverse:\nChange the order or perspective to see things differently.\nCase Study: Cirque du Soleil's reversal of traditional circus concepts.\nAdditional Insight: FBI's undercover operation using a wedding scenario to capture criminals.
Implementing SCAMPER:\nApply SCAMPER to each element of a challenge, exploring new ideas.\nEncourage exploring multiple options and returning to the original idea if it remains the best solution.\nEmphasize the importance of case studies in understanding and applying SCAMPER.
Concluding Thoughts:\nSCAMPER, a checklist of questions, can transform existing ideas into innovative solutions.\nIts flexibility makes it a valuable tool across various industries.\nBy repeatedly applying SCAMPER, one can discover unique, original ideas, fostering innovation and problem-solving."""

        bad_ex="""Mindful Mood Mixer (MMM) (Adapt)\nCore Idea: Mindful Mood Mixer (MMM) is a virtual reality (VR) system that integrates mindfulness and meditation into a personalized VR experience. It adapts a concept similar to Emotional VR, where the VR environment responds to the user's emotional state. In MMM, this environment is tailored to guide users through mindfulness and meditation practices based on their current emotional state, detected through biometric readings. The aim is to provide immediate emotional relief while fostering long-term emotional regulation and resilience through mindfulness techniques.\n"""
        good_ex="""Mindful Mood Mixer (MMM) (Adapt)\nCore Idea: Mindful Mood Mixer (MMM) is a pioneering virtual reality system focused on enhancing mental well-being through personalized mindfulness and meditation experiences. This system uses advanced biometric monitoring to gauge a user's emotional state, then adapts its VR environment accordingly to provide tailored mindfulness and meditation practices. The concept is to offer immediate emotional support while also cultivating long-term emotional resilience and mindfulness skills.\n"""
        
        b_improve_example="""Emotional VR
Core Idea:Emotional VR is an innovative virtual reality system that provides customized emotional experiences based on individual users' emotional states. By analyzing biometric signals such as heart rate and skin conductance to interpret emotions, the system dynamically alters the VR environment based on these readings. This assists users in appropriately controlling their emotions and guiding them in a positive direction. The technology enables users not only to understand their emotions but also to actively manage them and learn methods to reduce stress.
Technologies and Materials Used:The system utilizes sensor technology for biometric signal recognition, machine learning algorithms for emotion analysis, and a 3D graphics engine to create a dynamic VR environment that responds to emotions. Additionally, it incorporates high-quality audio output and voice guides that use a psychological approach to enhance user immersion.
Revised Approach to Problem-Solving:The system accurately reads users' current emotions and provides an environment that either amplifies those emotions or induces relaxation, thereby solving mental health issues. For example, a calming forest scene is provided for users feeling stress, aiding relaxation and supporting emotional control. When positive emotions are detected, the system offers social events within VR to further enhance users' sense of happiness.
Concrete Use Cases:For instance, a user returning home from a tiring day at work can use this system to experience a tranquil walk in the forest tailored to their day's stress level. On weekends, they can relive and share happy moments with family and friends in VR. Additionally, as part of mental health care, users can participate in guided meditation sessions led by psychotherapists in VR
"""
        user_template=f"""Please follow the (guide) below and come up with five ideas that expand on (base_idea). Of course, it is important that these ideas are also ideas that solve (issue).Each idea should be described in about 450 words. However, each idea must conform to the (format). The brackets [] in the format are explanations of what should be written. For example, where it says [specific number], actually insert a specified matter like 2000. Parts like core idea: do not need to be changed.In addition, since developed ideas will be presented on a separate occasion from (base_idea), please do not mention (base_idea) in the idea document, e.g., "improve (base_idea)". In other words, (bad_ex) and (good_ex) are documents about the same idea, but should be written like (good_ex).\n
Format:{improve_format}\n
Guide:{scamper}\n
bad_ex:{bad_ex}\n
good_ex:{good_ex}\n\n"""

        user_example_message=f"""{user_template}
base_idea:{b_improve_example}
problem:How to use information technology to enrich people's emotions"""

        assistant_answer_message="""Idea1:Social Emotion VR (Substitute)\nCore Idea:Social Emotion VR is a groundbreaking virtual reality platform meticulously designed to foster deep emotional connections and community engagement in a digital space. This innovative system enables users to share and communicate their emotional states in real-time with others, creating a support network within the virtual world. It serves as a digital sanctuary for users to seek comfort, understanding, or shared joy, aligning with their emotional needs at any given moment.\nTechnologies and Materials Used:The platform utilizes advanced sensor technology for real-time emotion detection. These sensors are capable of accurately interpreting subtle changes in the user’s emotional state. Combined with sophisticated machine learning models, the platform analyzes emotional data to create a responsive virtual environment that reflects the user’s feelings. It is also equipped with a robust 3D graphics engine, delivering an immersive and visually engaging experience. Additionally, the platform ensures user privacy and safety through secure privacy controls and interactive tools, creating a safe space for emotional expression and management.\nRevised Approach to Problem-Solving:Social Emotion VR takes an innovative approach to mental health by offering adaptive virtual scenarios that mirror users' emotional states. It is designed to encourage a balanced emotional life, where stressful emotions trigger serene and peaceful settings, while joyful states activate interactive and celebratory spaces. This dynamic environment enhances the overall emotional well-being of the user by providing a tailored virtual experience that addresses their current emotional needs.\nConcrete Use Cases:This platform has diverse applications, such as providing a tranquil forest environment for a user dealing with daily stressors, offering a peaceful escape to decompress and relax. Conversely, for those seeking social engagement, it provides vibrant virtual gatherings for interaction and shared joy. The platform also has therapeutic applications, offering guided relaxation sessions developed by mental health professionals, making it a versatile tool for emotional wellness and community building.\n
Idea2:Relaxation Therapy VR(combine)\nCore Idea:Relaxation Therapy VR is not just a tool; it’s a revolution in the world of mental wellness. This system combines the immersive power of virtual reality with scientifically-proven relaxation and meditation techniques. Imagine stepping into a world where every element is tailored to soothe your mind and alleviate stress. The core of this system lies in creating personal sanctuaries, offering users an escape into peaceful landscapes that promote mental clarity and stress reduction. It's like having a personal retreat accessible at any time, right in your home.\nTechnologies and Materials Used:At the heart of Relaxation Therapy VR is environmental biofeedback technology. This advanced system uses physiological markers such as heart rate variability to create a deeply personalized meditation experience. By responding to each user's unique bio-signals, the system adjusts the virtual environment, ensuring maximum relaxation and effectiveness. The combination of serene visuals and sounds, alongside educational content about stress management, forms a comprehensive, holistic approach. This technology doesn't just replicate calming environments; it evolves with the user, creating an ever-improving, personalized relaxation journey.\nRevised Approach to Problem-Solving:Relaxation Therapy VR is designed to tackle stress and anxiety by providing a complete immersion in tranquil virtual environments. The real-time biofeedback ensures that each session is tailored to the individual’s current state, enhancing the effectiveness of relaxation practices. This approach goes beyond traditional relaxation methods, using the latest in VR and biofeedback technology to address stress and anxiety in a modern, personalized way.\nConcrete Use Cases:The versatility of Relaxation Therapy VR is remarkable. Users can engage in guided meditation journeys, participate in virtual yoga classes, or simply relax in beautifully rendered natural environments. The system adapts to various mental health needs, making it an invaluable tool for daily relaxation routines and structured therapeutic programs. Whether for a quick stress-relief session or a comprehensive mental health regimen, Relaxation Therapy VR offers a multitude of engaging and beneficial activities.\n
Idea3:Creative Expression VR(Adapt)\nCore Idea:Creative Expression VR is a groundbreaking platform that redefines artistic expression. This innovative system offers a virtual space where users can harness their emotions and channel them into creative pursuits. The platform allows users to visualize and materialize their feelings using various artistic mediums, transforming the VR space into a canvas for emotional exploration and expression. It’s a therapeutic venture, offering a satisfying and unique outlet for users to express themselves creatively.\nTechnologies and Materials Used:Creative Expression VR is equipped with a diverse array of digital tools. Users can engage in painting, sculpting, music composition, and even virtual performances within a studio setting. It supports a wide range of artistic activities and includes a virtual gallery for community interactions and feedback. This platform is not just about creating art; it's about experiencing and sharing it in a dynamic, interactive environment.\nRevised Approach to Problem-Solving:Using art as a tool for emotional catharsis and personal growth, Creative Expression VR provides a safe and inspiring environment for users to explore and express their innermost feelings. The platform is designed to encourage self-exploration and emotional expression through creative means, offering an innovative approach to dealing with emotional challenges.\nConcrete Use Cases:Creative Expression VR caters to both beginners and seasoned artists. It offers creative workshops, peer sharing opportunities, and exploration of new artistic realms. This platform is especially beneficial for those seeking creative outlets to improve emotional well-being. Whether it’s experimenting with new art forms or refining existing skills, Creative Expression VR provides a space where art and emotion intersect, offering a unique and therapeutic experience for all users.
Idea4:EmoSphere VR(Modify)\nCore Idea:EmoSphere VR represents a significant leap forward in virtual reality technology, introducing a unique spherical display that fully immerses the user in a 360-degree environment. This advanced system is meticulously designed to enhance the user's sensory engagement, delivering a comprehensive and all-encompassing experience that deeply resonates with their emotional states. The primary aim of EmoSphere VR is to create an environment that not only entertains but also deeply connects with the user on an emotional level, providing an unparalleled experience in virtual reality.\nTechnologies and Materials Used:EmoSphere VR integrates a host of sophisticated technologies to achieve its revolutionary experience. At the forefront is the spherical display, which envelopes the user in a fully immersive visual field. This display is complemented by state-of-the-art surround sound systems, creating an auditory experience that is just as rich and enveloping as the visual one. Additionally, the system includes multi-directional haptic feedback mechanisms, allowing users to feel and interact with the virtual environment in a tactile and realistic manner.The system's emotional responsiveness is powered by advanced biometric sensors. These sensors are capable of detecting subtle changes in the user's physiological states, such as heart rate, skin temperature, and even minute facial expressions. Coupled with sophisticated AI algorithms, these sensors allow EmoSphere VR to analyze and respond to the user's emotional state in real-time, adapting the virtual environment to enhance or soothe their emotions.\nRevised Approach to Problem-Solving:The innovative approach of EmoSphere VR lies in its ability to create a virtual environment that is not just visually and audibly immersive but also emotionally resonant. Traditional VR systems focus on visual and auditory immersion, but EmoSphere VR takes this a step further by integrating emotional resonance into the experience. This approach facilitates a deeper level of emotional exploration and healing, as the environment can be tailored to evoke or soothe specific emotions.\nConcrete Use Cases:EmoSphere VR finds its applications in a variety of scenarios. For individuals seeking tranquility and relaxation, the system can immerse them in a serene forest environment, complete with the sounds of nature and a calming visual palette. Every element, from the rustling of leaves to the gentle flow of a stream, is rendered in stunning detail, providing a deeply relaxing experience.
Idea5:Reverse Emotion VR(Reverse)\nCore Idea:Reverse Emotion VR introduces an innovative twist to the virtual reality experience by presenting users with pre-determined emotional environments. This system is designed to challenge the user's emotional adaptability and resilience. Unlike traditional VR systems that cater to the user's current emotional state, Reverse Emotion VR takes the opposite approach. It presents users with a variety of emotional scenarios, requiring them to adapt and respond accordingly. This unique method aims to build emotional strength and flexibility, allowing users to handle a wider range of emotional situations effectively.\nTechnologies and Materials Used:Reverse Emotion VR utilizes established VR technologies, including dynamic environments and precise biometric sensors, to create a responsive and interactive experience. The system's dynamic environments are designed to simulate various emotional scenarios vividly. The biometric sensors play a crucial role in monitoring the user's responses to these scenarios, providing feedback to the system to adjust the experience in real-time.\nRevised Approach to Problem-Solving:The innovative aspect of Reverse Emotion VR is its reversed interaction pattern. Instead of a VR system that adapts to the user's current emotions, it presents pre-set emotional scenarios for the user to experience and adapt to. This reversal challenges the user to practice emotional regulation and adaptability in a controlled yet diverse range of situations, enhancing their ability to handle real-life emotional challenges.\nConcrete Use Cases:Reverse Emotion VR is particularly beneficial in professional training and personal development contexts. For instance, therapists can use this system to prepare themselves for a wide range of emotional situations they might encounter with clients. Educators and first responders can also benefit from this training, as it prepares them to remain calm and focused in high-stress or emotionally charged scenarios.In a personal development context, users can use Reverse Emotion VR to practice and improve their emotional regulation skills. They might be placed in a simulated high-stress environment, such as a busy workplace, and learn techniques to maintain calmness and focus. Conversely, in an environment of overwhelming joy and excitement, users can practice grounding techniques to maintain emotional balance. This system's versatility makes it a valuable tool for anyone looking to enhance their emotional intelligence and resilience."""
        
        user_message=f"""{user_template}base_idea:{self.serializeDict(origin_idea)}\nproblem:{self.problem}"""

        message=f""""role":"system", "content":{system_message},
                "role":"user", "content":{user_example_message },
                "role":"assistant", "content": {assistant_answer_message},
                "role":"user","content":{user_message}"""
                
        api_response=self.client.generate_content(message).text
        normalized_list=self._extractIdea(api_response)
        print(f"list長:{str(len(normalized_list))}")
        if len(normalized_list)==0:
            print(api_response)
        self.all_improve_idea.extend(normalized_list)
        logger.log(logging.INFO,f"scamper(アイデア向上)の{num}つ目の完了")
        